columns:
  age : float
  sex : category
  bmi : float
  children : float
  smoker : category
  region : category
  expenses : float

numerical_columns:
  - age
  - bmi
  - children

categorical_columns:
  - sex
  - smoker
  - region

target_column: expenses

domain_value:
  sex:
    - male
    - female

  region:
    - southeast
    - southwest
    - northwest
    - northeast